BEGIN
    FOR t IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name IN (
            'AUTHOR_ACCOUNT_REQUEST','ADMIN_LOG','REPORT','AUTHOR_REVIEW',
            'POST_LIKE','POST_COMMENT','POST','IDEAL_MATCH','IDEAL_RUN','IDEAL_TEMPLATE_ITEM','IDEAL_TEMPLATE','IDEAL_RESULT',
            'TIER_ITEM','TIER_LIST','TIER_TEMPLATE_ITEM','TIER_TEMPLATE','RATING','BOOK',
            'AUTHOR_ACCOUNT','AUTHOR','MEMBER'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/
/*END*/
BEGIN
    FOR s IN (
        SELECT sequence_name
        FROM user_sequences
        WHERE sequence_name IN (
            'SEQ_MEMBER','SEQ_AUTHOR','SEQ_BOOK','SEQ_RATING',
            'SEQ_TIER_TEMPLATE','SEQ_TIER_TEMPLATE_ITEM','SEQ_TIER_LIST','SEQ_TIER_ITEM','SEQ_IDEAL_TEMPLATE','SEQ_IDEAL_TEMPLATE_ITEM','SEQ_IDEAL_RUN','SEQ_IDEAL_MATCH','SEQ_IDEAL_RESULT',
            'SEQ_POST','SEQ_POST_COMMENT','SEQ_POST_LIKE',
            'SEQ_AUTHOR_REVIEW','SEQ_REPORT','SEQ_ADMIN_LOG','SEQ_AUTHOR_REQ'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/
/*END*/

CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_AUTHOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_BOOK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_RATING START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_TIER_TEMPLATE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_TIER_TEMPLATE_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_TIER_LIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_TIER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_IDEAL_RESULT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_IDEAL_TEMPLATE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_IDEAL_TEMPLATE_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_IDEAL_RUN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_IDEAL_MATCH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_POST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_POST_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_POST_LIKE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_AUTHOR_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_REPORT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_ADMIN_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/
CREATE SEQUENCE SEQ_AUTHOR_REQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/*END*/

CREATE TABLE MEMBER (
    member_id NUMBER NOT NULL,
    login_id VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    nickname VARCHAR2(30 CHAR) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    role VARCHAR2(10) DEFAULT 'USER' NOT NULL,
    fail_count NUMBER DEFAULT 0 NOT NULL,
    is_locked CHAR(1) DEFAULT 'N' NOT NULL,
    last_login_at DATE,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY(member_id),
    CONSTRAINT UK_MEMBER_LOGIN UNIQUE(login_id),
    CONSTRAINT UK_MEMBER_NICKNAME UNIQUE(nickname),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE(email),
    CONSTRAINT CK_MEMBER_ROLE CHECK(role IN ('USER','ADMIN')),
    CONSTRAINT CK_MEMBER_FAIL CHECK(fail_count >= 0),
    CONSTRAINT CK_MEMBER_LOCK CHECK(is_locked IN ('Y','N'))
);
/*END*/

CREATE TABLE AUTHOR (
    author_id NUMBER NOT NULL,
    author_name VARCHAR2(100) NOT NULL,
    bio VARCHAR2(1000),
    CONSTRAINT PK_AUTHOR PRIMARY KEY(author_id)
);
/*END*/

CREATE INDEX IDX_AUTHOR_NAME_LOWER ON AUTHOR(LOWER(author_name));
/*END*/

CREATE TABLE AUTHOR_ACCOUNT (
    member_id NUMBER NOT NULL,
    linked_author_id NUMBER,
    verified_at DATE,
    self_intro VARCHAR2(1000),
    self_intro_updated_at DATE,
    CONSTRAINT PK_AUTHOR_ACCOUNT PRIMARY KEY(member_id),
    CONSTRAINT FK_AUTHACC_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_AUTHACC_AUTHOR FOREIGN KEY(linked_author_id) REFERENCES AUTHOR(author_id) ON DELETE SET NULL,
    CONSTRAINT UK_AUTHACC_AUTHOR UNIQUE(linked_author_id)
);
/*END*/

CREATE TABLE BOOK (
    book_id NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    genre VARCHAR2(50) NOT NULL,
    publisher VARCHAR2(100),
    published_date DATE,
    description VARCHAR2(2000),
    image_url VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT PK_BOOK PRIMARY KEY(book_id),
    CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY(author_id) REFERENCES AUTHOR(author_id),
    CONSTRAINT CK_BOOK_STATUS CHECK(status IN ('PENDING','APPROVED','REJECTED'))
);
/*END*/

CREATE INDEX IDX_BOOK_TITLE_LOWER ON BOOK(LOWER(title));
/*END*/

CREATE INDEX IDX_BOOK_STATUS_GENRE ON BOOK(status, genre, book_id);
/*END*/

CREATE TABLE RATING (
    rating_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    score NUMBER(1) NOT NULL,
    comment_text VARCHAR2(500),
    CONSTRAINT PK_RATING PRIMARY KEY(rating_id),
    CONSTRAINT FK_RATING_BOOK FOREIGN KEY(book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE,
    CONSTRAINT FK_RATING_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT UK_RATING_BOOK_MEMBER UNIQUE(book_id, member_id),
    CONSTRAINT CK_RATING_SCORE CHECK(score BETWEEN 1 AND 5)
);
/*END*/

CREATE INDEX IDX_RATING_MEMBER_BOOK ON RATING(member_id, book_id);
/*END*/

CREATE TABLE TIER_TEMPLATE (
    template_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    category VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    admin_id NUMBER,
    reject_reason VARCHAR2(1000),
    requested_at DATE DEFAULT SYSDATE NOT NULL,
    processed_at DATE,
    CONSTRAINT PK_TIER_TEMPLATE PRIMARY KEY(template_id),
    CONSTRAINT FK_TTPL_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_TTPL_ADMIN FOREIGN KEY(admin_id) REFERENCES MEMBER(member_id) ON DELETE SET NULL,
    CONSTRAINT CK_TTPL_CATEGORY CHECK(category IN ('자유','장르','작가')),
    CONSTRAINT CK_TTPL_STATUS CHECK(status IN ('PENDING','APPROVED','REJECTED'))
);
/*END*/

CREATE TABLE TIER_TEMPLATE_ITEM (
    template_item_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    sort_order NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TIER_TEMPLATE_ITEM PRIMARY KEY(template_item_id),
    CONSTRAINT FK_TTITEM_TEMPLATE FOREIGN KEY(template_id) REFERENCES TIER_TEMPLATE(template_id) ON DELETE CASCADE,
    CONSTRAINT FK_TTITEM_BOOK FOREIGN KEY(book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE,
    CONSTRAINT UK_TTITEM_BOOK UNIQUE(template_id, book_id)
);
/*END*/

CREATE INDEX IDX_TTITEM_BOOK_TEMPLATE ON TIER_TEMPLATE_ITEM(book_id, template_id);
/*END*/

CREATE TABLE TIER_LIST (
    tier_list_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    is_public CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TIER_LIST PRIMARY KEY(tier_list_id),
    CONSTRAINT FK_TIERLIST_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_TIERLIST_TEMPLATE FOREIGN KEY(template_id) REFERENCES TIER_TEMPLATE(template_id),
    CONSTRAINT UK_TIERLIST_MEMBER_TEMPLATE UNIQUE(member_id, template_id),
    CONSTRAINT CK_TIERLIST_PUBLIC CHECK(is_public IN ('Y','N'))
);
/*END*/

CREATE INDEX IDX_TIERLIST_TEMPLATE ON TIER_LIST(template_id);
/*END*/

CREATE TABLE TIER_ITEM (
    tier_item_id NUMBER NOT NULL,
    tier_list_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    tier_grade VARCHAR2(10) NOT NULL,
    sort_order NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TIER_ITEM PRIMARY KEY(tier_item_id),
    CONSTRAINT FK_TIERITEM_LIST FOREIGN KEY(tier_list_id) REFERENCES TIER_LIST(tier_list_id) ON DELETE CASCADE,
    CONSTRAINT FK_TIERITEM_BOOK FOREIGN KEY(book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE,
    CONSTRAINT UK_TIERITEM_BOOK UNIQUE(tier_list_id, book_id),
    CONSTRAINT CK_TIERITEM_GRADE CHECK(tier_grade IN ('S','A','B','C','D')),
    CONSTRAINT CK_TIERITEM_ORDER CHECK(sort_order >= 0)
);
/*END*/

CREATE TABLE IDEAL_TEMPLATE (
    template_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    category VARCHAR2(20) DEFAULT '자유' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_IDEAL_TEMPLATE PRIMARY KEY(template_id),
    CONSTRAINT FK_IDEALT_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT CK_IDEALT_CATEGORY CHECK(category IN ('자유','장르'))
);
/*END*/

CREATE TABLE IDEAL_TEMPLATE_ITEM (
    template_item_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    sort_order NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_IDEAL_TEMPLATE_ITEM PRIMARY KEY(template_item_id),
    CONSTRAINT FK_IDEALTI_TEMPLATE FOREIGN KEY(template_id) REFERENCES IDEAL_TEMPLATE(template_id) ON DELETE CASCADE,
    CONSTRAINT FK_IDEALTI_BOOK FOREIGN KEY(book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE,
    CONSTRAINT UK_IDEALTI_BOOK UNIQUE(template_id, book_id)
);
/*END*/

CREATE TABLE IDEAL_RUN (
    run_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    bracket_size NUMBER NOT NULL,
    winner_book_id NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_IDEAL_RUN PRIMARY KEY(run_id),
    CONSTRAINT FK_IDEALRUN_TEMPLATE FOREIGN KEY(template_id) REFERENCES IDEAL_TEMPLATE(template_id) ON DELETE CASCADE,
    CONSTRAINT FK_IDEALRUN_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_IDEALRUN_WINNER FOREIGN KEY(winner_book_id) REFERENCES BOOK(book_id),
    CONSTRAINT UK_IDEALRUN_MEMBER_TEMPLATE UNIQUE(member_id, template_id),
    CONSTRAINT CK_IDEALRUN_SIZE CHECK(bracket_size IN (8,16))
);
/*END*/

CREATE INDEX IDX_IDEALRUN_TEMPLATE ON IDEAL_RUN(template_id, member_id);
/*END*/

CREATE TABLE IDEAL_MATCH (
    match_id NUMBER NOT NULL,
    run_id NUMBER NOT NULL,
    round_size NUMBER NOT NULL,
    match_order NUMBER NOT NULL,
    left_book_id NUMBER NOT NULL,
    right_book_id NUMBER NOT NULL,
    winner_book_id NUMBER NOT NULL,
    CONSTRAINT PK_IDEAL_MATCH PRIMARY KEY(match_id),
    CONSTRAINT FK_IDEALMATCH_RUN FOREIGN KEY(run_id) REFERENCES IDEAL_RUN(run_id) ON DELETE CASCADE,
    CONSTRAINT FK_IDEALMATCH_LEFT FOREIGN KEY(left_book_id) REFERENCES BOOK(book_id),
    CONSTRAINT FK_IDEALMATCH_RIGHT FOREIGN KEY(right_book_id) REFERENCES BOOK(book_id),
    CONSTRAINT FK_IDEALMATCH_WINNER FOREIGN KEY(winner_book_id) REFERENCES BOOK(book_id),
    CONSTRAINT UK_IDEALMATCH_ORDER UNIQUE(run_id, round_size, match_order),
    CONSTRAINT CK_IDEALMATCH_ROUND CHECK(round_size IN (2,4,8,16))
);
/*END*/

CREATE TABLE POST (
    post_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    tier_list_id NUMBER,
    category VARCHAR2(30) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    genre VARCHAR2(50),
    tag VARCHAR2(200),
    view_count NUMBER DEFAULT 0 NOT NULL,
    is_pinned CHAR(1) DEFAULT 'N' NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_POST PRIMARY KEY(post_id),
    CONSTRAINT FK_POST_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_POST_TIER_LIST FOREIGN KEY(tier_list_id) REFERENCES TIER_LIST(tier_list_id) ON DELETE SET NULL,
    CONSTRAINT UK_POST_TIER_LIST UNIQUE(tier_list_id),
    CONSTRAINT CK_POST_CATEGORY CHECK(category IN ('FREE','REVIEW','RECOMMEND','TIER','AUTHOR','NOTICE')),
    CONSTRAINT CK_POST_VIEW CHECK(view_count >= 0),
    CONSTRAINT CK_POST_PINNED CHECK(is_pinned IN ('Y','N'))
);
/*END*/

CREATE TABLE POST_COMMENT (
    comment_id NUMBER NOT NULL,
    post_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    parent_comment_id NUMBER,
    content VARCHAR2(1000) NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_POST_COMMENT PRIMARY KEY(comment_id),
    CONSTRAINT UK_COMMENT_POST UNIQUE(post_id, comment_id),
    CONSTRAINT FK_COMMENT_POST FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_PARENT FOREIGN KEY(post_id, parent_comment_id) REFERENCES POST_COMMENT(post_id, comment_id)
);
/*END*/

CREATE TABLE POST_LIKE (
    post_like_id NUMBER NOT NULL,
    post_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_POST_LIKE PRIMARY KEY(post_like_id),
    CONSTRAINT FK_POSTLIKE_POST FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE,
    CONSTRAINT FK_POSTLIKE_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT UK_POSTLIKE_MEMBER UNIQUE(post_id, member_id)
);
/*END*/

CREATE TABLE AUTHOR_REVIEW (
    author_review_id NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    is_spoiler CHAR(1) DEFAULT 'N' NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT PK_AUTHOR_REVIEW PRIMARY KEY(author_review_id),
    CONSTRAINT FK_AREVIEW_AUTHOR FOREIGN KEY(author_id) REFERENCES AUTHOR(author_id) ON DELETE CASCADE,
    CONSTRAINT FK_AREVIEW_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT CK_AREVIEW_SPOILER CHECK(is_spoiler IN ('Y','N'))
);
/*END*/

CREATE TABLE REPORT (
    report_id NUMBER NOT NULL,
    reporter_id NUMBER NOT NULL,
    target_type VARCHAR2(30) NOT NULL,
    target_id NUMBER NOT NULL,
    reason_type VARCHAR2(30) NOT NULL,
    reason_detail VARCHAR2(1000),
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    admin_id NUMBER,
    admin_memo VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    processed_at DATE,
    CONSTRAINT PK_REPORT PRIMARY KEY(report_id),
    CONSTRAINT FK_REPORT_REPORTER FOREIGN KEY(reporter_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_REPORT_ADMIN FOREIGN KEY(admin_id) REFERENCES MEMBER(member_id) ON DELETE SET NULL,
    CONSTRAINT CK_REPORT_TARGET CHECK(target_type IN ('POST','COMMENT','AUTHOR_REVIEW')),
    CONSTRAINT UK_REPORT_TARGET UNIQUE(reporter_id, target_type, target_id)
);
/*END*/

CREATE TABLE ADMIN_LOG (
    admin_log_id NUMBER NOT NULL,
    admin_id NUMBER NOT NULL,
    target_type VARCHAR2(30) NOT NULL,
    target_id NUMBER NOT NULL,
    action_type VARCHAR2(30) NOT NULL,
    reason VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ADMIN_LOG PRIMARY KEY(admin_log_id),
    CONSTRAINT FK_ADMINLOG_MEMBER FOREIGN KEY(admin_id) REFERENCES MEMBER(member_id)
);
/*END*/

CREATE TABLE AUTHOR_ACCOUNT_REQUEST (
    request_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    author_id NUMBER,
    introduction VARCHAR2(2000),
    proof_url VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    admin_id NUMBER,
    reject_reason VARCHAR2(1000),
    requested_at DATE DEFAULT SYSDATE NOT NULL,
    processed_at DATE,
    CONSTRAINT PK_AUTHOR_REQ PRIMARY KEY(request_id),
    CONSTRAINT FK_AREQ_MEMBER FOREIGN KEY(member_id) REFERENCES MEMBER(member_id) ON DELETE CASCADE,
    CONSTRAINT FK_AREQ_AUTHOR FOREIGN KEY(author_id) REFERENCES AUTHOR(author_id) ON DELETE SET NULL,
    CONSTRAINT FK_AREQ_ADMIN FOREIGN KEY(admin_id) REFERENCES MEMBER(member_id) ON DELETE SET NULL,
    CONSTRAINT CK_AREQ_STATUS CHECK(status IN ('PENDING','APPROVED','REJECTED'))
);
/*END*/
